version: "3.8"

services: 
  database: 
    image: mysql 
    environment: 
      MYSQL_ROOT_PASSWORD: admin 
      MYSQL_DATABASE: collab 

    command: --default-authentication-plugin=mysql_native_password 
    # ports: 
    #   - 4000:8080
    volumes: 
    - ./db_init:/docker-entrypoint-initdb.d 
    # mysql image will automatically run any .sql or .sh files in /docker-entrypoint-initdb.d

  backend: 
    build: ./
    ports: 
      - 8080:8080
    environment: 
      DB_URL: root:admin@tcp(database)/collab
      LOGS_ENABLE: 1 
    
    restart: unless-stopped 

    command: sh collab/docker-entrypoint.sh 

  # backend-test: 
  #     image: collab-story_backend 
  #     command: go test ./...


# To Run This > "docker-compose build" > "docker-compose up"